$(function() {

    //Populate using an object literal

    WTF.init({

        heading: [
            "[[ ENCLAVE DATABANK // ACCESSING BOUNTIES... ]]<br><br>[[ BOUNTIES LOADED ]]"
        ],
        response: [
           "[[ RETRIEVE BOUNTY HUNT ]]"
        ],
        template: [
		"You'll have to travel to @locale and @mission. The target is @target, known as @firstname @lastname. Be careful because @complication. @theme.",
		"Go to @locale and @mission. The target is @target, known as @firstname @lastname. You may encounter resistance in the form of @obstacle. @theme.",
		"Your Bounty requires you to go to @locale and @mission. The target is @target. Do not let your guard down, because @complication. @theme.",
		"The bounty requires you to infiltrate @group on @locale known as the @groupname1 @groupname2. You must kill them all. You may encounter difficulty in the form of @obstacle. @theme.",
        ],
        locale: [
		"Alderaan",
		"Balmorra",
		"Corellia",
		"Dantooine",
		"Hoth",
		"Hutta",
		"Nar Shaddaa",
		"Onderon",
		"Ord Mantell",
		"Rishi",
		"Taris",
		"Tatooine",
		"Zakuul"
        ],
        mission: [
		"assassinate the target silently",
		"kill the target",
		"eleminate the target",
		"capture the target alive",
		"find and eleminate the target",
		"find and capture the target alive",
		"find the target and bring them to the Enclave, dead or alive",
        ],
        behavior: [
	        "an abrasive",
		"an absent-minded",
		"an active",
		"an affable",
		"an aggrandizing",
		"an aloof",
		"an altruistic",
		"an amiable",
		"an anxious",
		"an apprehensive",
		"an argumentative",
		"an aspiring",
		"an authoritarian",
		"a belligerent",
		"a boisterous",
		"a calculating",
		"a candid",
		"a canny and experienced",
		"a capable",
		"a cheerful",
		"a clever",
		"a community-oriented",
		"a conceited",
		"a condescending",
		"a conscientious",
		"a controlling",
		"a courteous",
		"a daring",
		"a debonair",
		"a determined",
		"a diligent",
		"a direct",
		"a disagreeable",
		"a disparaging",
		"a draconian",	
		"an eccentric",
		"an economically ruthless",
		"an efficient",
		"an egotistical",
		"an empathetic",
		"an engaging",
		"an exacting",
		"a fiscally responsible",
		"a flamboyant",
		"a flighty",
		"a flustered",
		"a frugal",
		"a frustrated",
		"a garrulous",
		"a genial",
		"a goal oriented",
		"a greedy",
		"a gregarious",
		"a grieving",
		"a gruff",
		"a hesitant",
		"a humble",
		"an ill-tempered",
		"an impulsive",
		"an industrious",
		"an intelligent",
		"an intimidating",
		"an intrepid",
		"an irritable",
		"a jaded",
		"a materialistic",
		"a melodramatic",
		"a naive and inexperienced",
		"a negligent",
		"a no-nonsense",
		"an obsequious",
		"an opinionated",
		"an optimistic",
		"an organized",
		"an ostentatious",
		"an outgoing",
		"a paranoid",
		"a particular",
		"a patient",
		"a persistent",
		"a persuasive",
		"a pessimistic",
		"a philanthropic",
		"a placid", 
		"a pragmatic",
		"a pretentious",
		"a professional",
		"a punctual",
		"a quick-tempered",
		"a rambunctious",
		"a rational",
		"a recalcitrant",
		"a recently promoted",
		"a reclusive",
		"a refined",
		"a reliable",
		"a reluctant",
		"a reserved",
		"a resilient",
		"a resolute",
		"a responsible",
		"a risk-taking",
		"a scrupulous",
		"a shrewd",
		"a slovenly",
		"a sly",
		"a strict",
		"a strident",
		"a taciturn",
		"a tactful",
		"a temperamental",
		"a tenacious",
		"an unconventional",
		"an unpredictable",
		"an unscrupulous",
		"a vain",
		"a verbose",
		"a vindictive"
        ],
        target: [
		"human spice adict",
		"zabrak murderer",
		"gamorean gangster",
		"twi'lek smuggler",
		"ex imperial",
		"V.I.P. female twi'lek dancer, that is getting hired by high paying costumers. ",
		"old republic war veteran",
		"an Ex Jedi Padawan, but without his lightsaber. Still, they are dangerous",
		"Imperial deserter",
		"poor mercenary, desperate for a job",
		"owner of a fine restaurant who is in reality a dangerous canibal",
		"Republic deserter and now criminal",
		"ex imperial soldier, who got banned from the empire because of canibalism and still is on the run. Be careful of them",
		"smuggler",
		"ex imperial soldier, who betrayed the empire",
		"spice dealer",
		"swoop racer"
        ],
        group: [
		"a criminal syndicate",
		"a spice dealer gang",
		"a gang of miscreants",
		"a group of illegal weapon sellers",
		"a group of criminals",
		"a small criminal organization",
		"a group of bank robbers",
		"a small gang",
		"a small syndicate"
        ],
        complication: [
		"the target has a blaster and knows how to use it",
		"an unidentified person close to the target is a highly trained bodyguard",
		"the target is about to leave the planet in a few days, possibly never to be seen again",
		"the target is an Ex-Mandalorian and still has his Beskar Armor. Be sure to return it to the Enclave",
		"the target already knows that a bounty is on his head and may have prepared traps",
		"the target is inside a republic prison. You might have to sneak in there",
		"the target is a fantastic sniper and a master of stealth"
        ],
       
        obstacle: [

				
		"Two Ex-Mandalorian Guards, though without their beskar.",
		"Three Ex-Mandalorian Guards, though without their beskar.",
		"Two Mercenary Guards, though with heavy durasteel armor.",
		"Three Mercenary Guards, all armed with heavy weapons.",
		"loyal bodyguards, that would do anything to protect your target",
		"a Bounty Hunter, that is outside of the enclave, and is after the target too. He is going to try to kill you, unless you manage to make a deal with him",
		"a Mandalorian Bounty Hunter, that is outside of the enclave, and is after the target too. He is going to try to kill you, unless you manage to make a deal with him",
		
        ],
        reason: [
		"who is out for revenge",
		"who is blackmailing the target",
		"who is acting for unknown reasons",
		"who is extorting the target",
		"who is pursuing misguided revenge",
		"who plans to kidnap the target",
		"who intends to assassinate the target",
		"who is the target's creditor",
		"who suspects the target is an Imperial contact"
        ],
        theme: [
		
		"Good luck. This is your chance to make yourself a name",
		"Leave no witnesses",
		"Be careful and good luck, Hunter",
		"Try to not get too much attention on yourself here",
        ],
		firstname: [
		"Manklo",
		"Njok",
		"Fibiw",
		"Bob",
		"Poolk",
		"Amanof",
		"Pinfo",
		"Lokos",
		"Pople",
		"Obamo",
		"Max",
		"Johnk",
		"Konst",
		"Philo",
		"Qau",
		"Wuio",
		"Erio",
		"Ryo",
		"Tnam",
		"Yyeem",
		"Ugan",
		"Iopna",
		"Oogwei",
		"Paau",
		"Alo",
		"Siuwq",
                "Ding", 
		"Plo",
		"Pees",
		"Ysu",
		"Iden"
	
		],
		lastname: [
		"Kalopne",
		"Mnagel",
		"Mnonee",
		"Uinga",
		"Yuojo",
		"Molovot",
		"Vinbva",
		"Zvee",
		"Iofaw",
		"Nawe",
		"Mnilik",
		"Baum",
		"Hose",
		"Airnil",
		"Brettni",
		"Ioln",
		"Hippot",
		"Judiah",
		"Koppy",
		"Laonme",
                "Zeez",
		"Xiom",
		"Chep",
		"Vaenoalo",
		"Beenop",
		"Niona",
		"Mimip",
		"Clean",
		"Osam"
		],
		groupname1: [
		"Black",
		"Red",
		"Yellow",
		"Orange",
		"White",
		"Blue",
		"Pink",
		"Green",
		"Grey",
		"Small",
		"Big",
		"Dark",
		"Light",
		"Heavy",
		"Hot",
		"Cold",
		"Drug",
		"Sneaky",
		"Mystic",
		"Fantastic",
		"Ugly",
		"Beautiful",
		"Fat",
		"Skinny"
		],
		groupname2: [
		"Eye",
		"Moon",
		"Planet",
		"Weapon",
		"Spice",
		"Gun",
		"Blaster",
		"Blood",
		"Raiders",
		"Hand",
		"Finger",
		"Foot",
	        "Botton",
		"Ocean",
		"Gangsters",
		"Dealers",
		"Haters",
		"Radicals",
		"Mandos, though they aren't and never were Mandos.",
		"Assassins",
		"Hunters"
		]
    });
	
});
