$(function() {

    //Populate using an object literal

    WTF.init({

        heading: [
            "[[ MANDALORIAN ENCLAVE // ACCESSING BOUNTIES... ]]<br><br>[[ BOUNTIES LOADED ]]"
        ],
        response: [
           "[[ RETRIEVE BOUNTY HUNT ]]"
        ],
        template: [
		"The bounty requires you to go to @locale and @mission. The target is @behavior @target. However, be careful because @complication. @theme.",
		"The bounty requires you to travel to @locale and obtain @asset from @behavior @target. You may encounter resistance in the form of @obstacle. @theme.",
		"Your task is to travel to @locale and @mission. The target is @behavior @target. You may encounter resistance in the form of @obstacle. @theme.",
		"Your task is to travel to @locale and @mission. The target is @behavior @target. However, be careful because @complication. @theme.",
		"The bounty requires you to protect @behavior @target on @locale from a hostile @target @reason. You may encounter resistance in the form of @obstacle. @theme.",
		"The bounty requires you to infiltrate @behavior @group on @locale and eleminate them. You may encounter difficulty in the form of @obstacle. @theme.",
        ],
        locale: [
		"Alderaan",
		"Balmorra",
		"Belsavis",
		"Cademimu V",
		"Corellia",
		"Mandalore",
		"Dantooine",
		"Dromund Kaas",
		"Hoth",
		"Hutta",
		"Nar Shaddaa",
		"Onderon",
		"Ord Mantell",
		"Quesh",
		"Rishi",
		"Tanaab",
		"Taris",
		"Tatooine",
		"Zakuul"
        ],
        mission: [
		"assassinate the target",
		"kill the target",
		"arrest the target",
		"capture the target",
		"find and eleminate the target",
		"find and capture the target",
		"kidnap the target",
		"find the target and bring him back, dead or alive",
		"get the target alive to the contract giver",
		"get the targets head back to the contract giver",
		"end the targets life",
        ],
        behavior: [
	        "an abrasive",
		"an absent-minded",
		"an active",
		"an affable",
		"an aggrandizing",
		"an aloof",
		"an altruistic",
		"an amiable",
		"an anxious",
		"an apprehensive",
		"an argumentative",
		"an aspiring",
		"an authoritarian",
		"a belligerent",
		"a boisterous",
		"a calculating",
		"a candid",
		"a canny and experienced",
		"a capable",
		"a cheerful",
		"a clever",
		"a community-oriented",
		"a conceited",
		"a condescending",
		"a conscientious",
		"a controlling",
		"a courteous",
		"a daring",
		"a debonair",
		"a determined",
		"a diligent",
		"a direct",
		"a disagreeable",
		"a disparaging",
		"a draconian",	
		"an eccentric",
		"an economically ruthless",
		"an efficient",
		"an egotistical",
		"an empathetic",
		"an engaging",
		"an exacting",
		"a fiscally responsible",
		"a flamboyant",
		"a flighty",
		"a flustered",
		"a frugal",
		"a frustrated",
		"a garrulous",
		"a genial",
		"a goal oriented",
		"a greedy",
		"a gregarious",
		"a grieving",
		"a gruff",
		"a hesitant",
		"a humble",
		"an ill-tempered",
		"an impulsive",
		"an industrious",
		"an intelligent",
		"an intimidating",
		"an intrepid",
		"an irritable",
		"a jaded",
		"a materialistic",
		"a melodramatic",
		"a naive and inexperienced",
		"a negligent",
		"a no-nonsense",
		"an obsequious",
		"an opinionated",
		"an optimistic",
		"an organized",
		"an ostentatious",
		"an outgoing",
		"a paranoid",
		"a particular",
		"a patient",
		"a persistent",
		"a persuasive",
		"a pessimistic",
		"a philanthropic",
		"a placid", 
		"a pragmatic",
		"a pretentious",
		"a professional",
		"a punctual",
		"a quick-tempered",
		"a rambunctious",
		"a rational",
		"a recalcitrant",
		"a recently promoted",
		"a reclusive",
		"a refined",
		"a reliable",
		"a reluctant",
		"a reserved",
		"a resilient",
		"a resolute",
		"a responsible",
		"a risk-taking",
		"a scrupulous",
		"a shrewd",
		"a slovenly",
		"a sly",
		"a strict",
		"a strident",
		"a taciturn",
		"a tactful",
		"a temperamental",
		"a tenacious",
		"an unconventional",
		"an unpredictable",
		"an unscrupulous",
		"a vain",
		"a verbose",
		"a vindictive"
        ],
        target: [
		"human spice adict",
		"zabrak murderer",
		"escaped prisoner",
		"gamorean gangster",
		"twi'lek smuggler",
		"ex mandalorian and known bounty hunter in that area",
		"M1-4X droid, protecting republic troopers",
		"civic leader named Misavin Teahul",
		"ex imperial named Jamecri Modesmal",
		"female twi'lek dancer",
		"old republic war veteran known as Johnfred Braybur",
		"exporter of fine textiles",
		"exporter of luxury goods",
		"force-user named Abragor Towsea",
		"geologist",
		"grifter",
		"high-level corporate executive",
		"hutt",
		"Imperial deserter",
		"information broker",
		"local gang enforcer",
		"member of local law enforcement",
		"mercenary band",
		"mercenary",
		"mid-level corporate executive",
		"news reporter",
		"nurse",
		"owner of a fine restaurant who is in reality a dangerous devaronian canibal ",
		"owner of a small animal hospital who secretly eats the ill animals. The shop is well known in the area ",
		"worker of a shipping company who keeps stealing money from his boss",
		"owner of a sleazy diner who deals in secret with spice",
		"pair of siblings who run a scrapyard and killed a hutt trooper once",
		"politician up for re-election",
		"politician who corrupt ways are too bad for the city",
		"Republic deserter",
		"mad scientist",
		"scrapyard owner",
		"smuggler",
		"socialite",
		"ex imperial soldier, who betrayed the empire",
		"spice dealer",
		"swoop racer",
		"tailor",
		"travelling merchant"
        ],
        group: [
		"criminal syndicate",
		"diplomat's staff",
		"gang of miscreants",
		"managing team of a corporation",
		"noble's household staff",
		"pirate encampment",
		"politician's staff",
		"small gang",
		"smuggling ring"
        ],
        complication: [
		"the target is being protected by an unidentified bodyguard",
		"the target keeps exotic animals as security",
		"an unidentified person close to the target is a highly trained bodyguard",
		"the target is on the move",
		"the target is located in a remote location and travel will be difficult",
		"the target's appearance and exact identity is unknown",
		"the target employs a double for security",
		"the target is on the move and will be difficult to find",
		"the target has been accused of a crime",
		"the target is expecting hostile action",
		"the target is imprisoned",
		"the target is missing",
		"the target is hospitalized",
        ],
        asset: [
		"information revealing Republic movements",
		"intel regarding a Republic supply cache",
		"intel regarding a criminal organization's supply cache",
		"intel pertaining to the identity of a spy",
		"the identity of a traitor",
		"supplies",
		"blackmail material"
        ],
        obstacle: [
		"wildlife",
		"natural hazards",
		"harsh environmental phenomena",
		"roving outlaws",
		"capable and alert guards",
		"dangerous weather",
		"an epidemic in the sector",
		"a Republic patrol",
		"travel delays",
		"poorly trained guards",
		"a rioting populace"
        ],
        reason: [
		"who is out for revenge",
		"who is blackmailing the target",
		"who is acting for unknown reasons",
		"who is extorting the target",
		"who is pursuing misguided revenge",
		"who plans to kidnap the target",
		"who intends to assassinate the target",
		"who is the target's creditor",
		"who suspects the target is an Imperial contact"
        ],
        theme: [
		"Talk to the contract giver for more details. The coordinates to them are attached.",
		"A hutt hired you to do this. Do not disappoint him and feel free to travel to him for more details.",
		"Attached is his holo number of the contract giver",
		"Good luck. This is your chance to make yourself a name",
		"Leave no witnesses",
		"Be careful and good luck, Hunter",
		"Try to not get too much attention on yourself here",
        ]
    });
	
});